---
title: Crystal Seas Kayaking - Guide to the San Juan Islands
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:title/"
email: 
baseurl: "/guide"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-1231479-1
description: Crystal Seas Kayaking Guide of the San Juan Islands
url: https://www.crystalseas.com/guide/
twitter_username: 
default_img: 
 
# exclude:
# - _screenshots
# - Gemfile
# - Gemfile.lock
# - LICENSE.txt
# - README.md
markdown: kramdown
permalink: "/:year/:month/:day/:title/"
sass:
  style: compressed
plugins:
- jekyll-paginate
- jekyll-sitemap
- octopress-autoprefixer
# - jekyll/imgix
- jekyll-redirect-from
